version: '3.8'
services:
  spring-security:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8888:8888 
    depends_on:
    - postgres     

  postgres:
    container_name: postgre
    image: postgres
    environment:
      POSTGRES_USER: haribabu
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data

    ports:
    - "5432:5432"

    restart: unless-stopped

  pgadmin:
    container_name: pgadm
    image: dpage/pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-hari@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN-CONFIG-SERVER_MODE: "False"
    #      PGADMIN_LISTEN_PORT: 80

    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"

    restart: unless-stopped
volumes:
  db-data:
  pgadmin-data: