version: '3.8'
services:
  # spring-security:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8888:8888 
  #   depends_on:
  #   - postgres 
  # sonarqube:
  #   image: sonarqube:community
  #   depends_on:
  #     - postgres
  #   environment:
  #     SONAR_JDBC_URL: jdbc:postgresql://localhost:5432/postgres
  #     SONAR_JDBC_USERNAME: haribabu
  #     SONAR_JDBC_PASSWORD: password
  #   volumes:
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_extensions:/opt/sonarqube/extensions
  #     - sonarqube_logs:/opt/sonarqube/logs
  #   ports:
  #     - "9000:9000"    

  postgres:
    # container_name: postgre
    image: postgres
    environment:
      POSTGRES_USER: haribabu
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data # docker run -d --name postgres -e POSTGRES_USER=haribabu -e POSTGRES_PASSWORD=password -v postgres:/var/lib/postgresql/data -p 5432:5432 postgres:latest 

    ports:
    - "5432:5432"

    restart: unless-stopped

  pgadmin:
    # container_name: pgadm
    image: dpage/pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-hari@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN-CONFIG-SERVER_MODE: "False"
    #      PGADMIN_LISTEN_PORT: 80

    volumes:
      - pgadmin-data:/var/lib/pgadmin # docker run -d --name pgadmin -e PGADMIN_DEFAULT_EMAIL=haribabu@gmail.com -e PGADMIN_DEFAULT_PASSWORD=admin -e GADMIN-CONFIG-SERVER_MODE=False -p 5050:5050 dpage/pgadmin4:latest 
    ports:
      - "5050:80"

    restart: unless-stopped
volumes:
  db-data:
  pgadmin-data: